title:              BeerVise
description:        Pick the right beer for you!
author:             TooHotToHoot Team
baseurl:            "/BeerVise"
url:                "https://temryl.github.io"

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site