title:              BeerVise
description:        Data story for our project of the course CS-401/Applied Data Analysis (ADA)
author:             TooHotToHoot Team
baseurl:            "/BeerVise"
url:                "https://temryl.github.io"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
